### ISSUE TITLE
Audio Playback

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#3]
I got the audio button to work when clicking "open in browser" (in Chrome) but in the actual Rstudio webpage it doesn't work. Not sure if that issue will come up when the app is published. I've been working on different methods of solving it but nothing is working (yet!). If the file is MP3, the audio button will play anywhere, including Rstudio webpage, so I was trying to convert the wav file to mp3 (just in the audio section) but there is no R functions or R code that does that. There are a few shell scripts that I could potentially run to convert the files, but they require the user to download packages on their computer. I was wondering if you had any suggestions or ideas @hglanz? 
I committed the code just so I can start working on other issues in the meantime.

**Comment by hglanz** [comment]
@michalg04 Ah, hmmmm.....I've run into similar issues when viewing apps within the RStudio webpage in the sense that some features/things won't work there but will inside a regular webpage. So, you should feel free to post your own, running version of the app on your own shinyapps.io account if you can so that you can play around with it live yourself. Do you think you'll be able to do this?

I'll talk to my wife about WAV vs. MP3 files and probably bring it to Friday's meeting. Thanks!

**Comment by michalg04** [comment]
@hglanz I can do that! I have a shinyapp account so I'll play around with it there and see if the problem still occurs.
