### ISSUE TITLE
Updated Project Objectives

### ISSUE THREAD

**Issue by hglanz** [hglanz/AcousticsApp-Summer2019#5]
@michalg04 @mschrothglanz I've updated the Readme on the home page of the repo to reflect a revised set of objectives for the app and their priority. These are the existing issues and constitute everything we want to aim for outside of the segmentation tab, which we'd also like. 

We do not expect all of these things to get completed, but @michalg04 should use it as a guide for your work. Feel free to jump around to different items if you'd like. 

Because there are many, I will let you (@michalg04 ) create a new github issue whenever you begin work on an item but please make sure to do this so we can stay organized and documented. 

Please also tag @mschrothglanz from now on too so that she can weigh in on things :)

Let us know if you have any questions! Feel free to close this issue once you've seen it. Thanks!

**Comment by michalg04** [comment]
I started working on making start and end time for the play button like we talked about in the meeting so when the time changes in the sidebar, so does the audio playback. I'm also working on a segmentation tab. Should I pause those and do something else from the new objectives? Or should I continue to work on those? Asking because I didn't see the start/end time for playback as one of the objectives and wanted to make sure it's still a feature we want. Either way is good for me! 
@hglanz @mschrothglanz

**Comment by hglanz** [comment]
Thanks for the quick reply @michalg04 ! I guess I'm lumping the start/end time for playback in with the interactivity of the three graphs and having a play button at all. So yes, those are still features we want.

Continuing work on the play button stuff and the segmentation tab are great; no need to pause. Thanks!
